//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurifier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadsTable
    {
        public int Lead_Id { get; set; }
        public string LeadName { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string Mail_Id { get; set; }
        public string MobileNumber { get; set; }
        public string GeneratedBy { get; set; }
        public int Team_Id { get; set; }
        public string Manager { get; set; }
        public int RolesId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Descreption { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual Role Role { get; set; }
        public virtual TeamsTable TeamsTable { get; set; }
    }
}
